import random
from turtle import fd, bk, rt, lt, up, down, tracer, goto, speed, fillcolor, begin_fill, end_fill
#tracer(0,1)
speed('fastest')
def kwadr(roz,kol):
    fillcolor(kol)
    begin_fill()
    for i in range(4):
        fd(roz)
        rt(90)
    end_fill()
R=12
def chod1(n,kl):
    for i in range(n):
        kwadr(R,kl)
        fd(R)
        
def chod2(n,kl):
    for i in range(n):
        kwadr(R,kl)
        rt(90)
        fd(R)
        lt(90)
        
def chod3(n,m):
    up()
    bk(n*R)
    rt(90)
    fd(m*R)
    lt(90)
    down()
def chod4(n,m):
    up()
    bk(n*R)
    lt(90)
    fd(m*R)
    rt(90)
    down()

def cyf(n):
    kolor=(random.random(),random.random(),random.random())
    if n=='0':
        chod1(3,kolor)
        rt(90)
        fd(R)
        lt(90)
        chod2(3,kolor)
        bk(4*R)
        lt(90)
        fd(3*R)
        rt(90)
        chod2(3,kolor)
        fd(R)
        chod1(3,kolor)
        chod4(-3,4)
    elif n=='1':
        chod2(4,kolor)
        bk(R)
        chod1(3,kolor)
        bk(3*R)
        lt(90)
        up()
        fd(3*R)
        rt(90)
        down()
        kwadr(R,kolor)
        chod4(-5,1)
    elif n=='2':
        chod1(3,kolor)
        rt(90)
        fd(R)
        lt(90)
        kwadr(R,kolor)
        chod3(2,1)
        chod1(2,kolor)
        chod3(3,1)
        kwadr(R,kolor)
        chod3(1,1)
        chod1(5,kolor)
        chod4(5,3)
        kwadr(R,kolor)
        chod4(-7,1)
    elif n=='3':
        up()
        bk(R)
        down()
        chod1(4,kolor)
        chod3(0,1)
        kwadr(R,kolor)
        chod3(3,1)
        chod1(3,kolor)
        chod3(0,1)
        kwadr(R,kolor)
        chod3(4,1)
        chod1(4,kolor)
        chod4(-3,4)
    elif n=='4':
        kwadr(R,kolor)
        chod3(1,1)
        kwadr(R,kolor)
        chod3(0,1)
        chod1(5,kolor)
        chod3(3,1)
        chod2(2,kolor)
        chod4(-5,5)
    elif n=='5':
        up()
        bk(R)
        down()
        chod1(5,kolor)
        chod3(5,1)
        chod2(1,kolor)
        chod1(4,kolor)
        chod3(0,1)
        kwadr(R,kolor)
        chod3(4,1)
        chod1(4,kolor)
        chod4(-3,4)
    elif n=='6':
        chod1(3,kolor)
        chod3(4,1)
        chod2(3,kolor)
        chod4(-1,2)
        chod1(3,kolor)
        chod3(0,1)
        kwadr(R,kolor)
        chod3(3,1)
        chod1(3,kolor)
        chod4(-3,4)
    elif n=='7':
        up()
        bk(R)
        down()
        chod1(5,kolor)
        chod3(2,1)
        kwadr(R,kolor)
        chod3(2,1)
        chod1(3,kolor)
        chod3(3,1)
        kwadr(R,kolor)
        chod3(1,1)
        kwadr(R,kolor)
        chod4(-7,4)
    elif n=='8':
        chod1(3,kolor)
        chod3(0,1)
        kwadr(R,kolor)
        chod3(4,0)
        kwadr(R,kolor)
        chod3(-1,1)
        chod1(3,kolor)
        chod3(0,1)
        kwadr(R,kolor)
        chod3(4,0)
        kwadr(R,kolor)
        chod3(-1,1)
        chod1(3,kolor)
        chod4(-3,4)
    elif n=='9':
        chod1(3,kolor)
        chod3(4,1)
        kwadr(R,kolor)
        chod3(-4,0)
        chod2(3,kolor)
        chod4(3,2)
        chod1(3,kolor)
        chod3(3,2)
        chod1(3,kolor)
        chod4(-3,4)
        
def narys(n):
    for i in range(len(str(n))):
       cyf(str(n)[i])

narys(2019)


